/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kassab10
 */
public class graphique1 extends javax.swing.JFrame {
    private Combinaisons jeu;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(graphique1.class.getName());

    /**
     * Creates new form graphique1
     */
    public graphique1() {
        initComponents();
        jeu = new Combinaisons();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        up_chiffre_1 = new javax.swing.JButton();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();
        up_chiffre_4 = new javax.swing.JButton();
        text_chiffre_0 = new javax.swing.JLabel();
        text_chiffre_1 = new javax.swing.JLabel();
        text_chiffre_2 = new javax.swing.JLabel();
        text_chiffre_3 = new javax.swing.JLabel();
        down_chiffre_1 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();
        bouton_tester = new javax.swing.JButton();
        text_lbl_nb_chiffres_exacts = new javax.swing.JLabel();
        text_nb_chiffres_exacts = new javax.swing.JLabel();
        text_lbl_nb_chiffres_haut = new javax.swing.JLabel();
        text_nb_chiffres_haut = new javax.swing.JLabel();
        text_lbl_nb_chiffres_bas = new javax.swing.JLabel();
        text_nb_chiffre_bas = new javax.swing.JLabel();
        texte_score = new javax.swing.JLabel();
        text_tentatives = new javax.swing.JLabel();
        bouton_recommencer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        up_chiffre_1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        up_chiffre_1.setText("^");
        up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_1ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 54, -1, -1));

        up_chiffre_2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        up_chiffre_2.setText("^");
        up_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_2ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 54, -1, -1));

        up_chiffre_3.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        up_chiffre_3.setText("^");
        up_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_3ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 54, -1, -1));

        up_chiffre_4.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        up_chiffre_4.setText("^");
        up_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_4ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 40, 26, -1));

        text_chiffre_0.setText("0");
        getContentPane().add(text_chiffre_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 123, 22, 35));

        text_chiffre_1.setText("0");
        getContentPane().add(text_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 125, 26, 34));

        text_chiffre_2.setText("0");
        getContentPane().add(text_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 122, 25, 37));

        text_chiffre_3.setText("0");
        getContentPane().add(text_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 81, 19, 50));

        down_chiffre_1.setText("down");
        down_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_1ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 173, -1, -1));

        down_chiffre_2.setText("Down");
        down_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_2ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 173, -1, -1));

        down_chiffre_3.setText("Down");
        down_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_3ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 173, -1, -1));

        down_chiffre_4.setText("Down");
        down_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_4ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 173, -1, -1));

        bouton_tester.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        bouton_tester.setText("Tester");
        bouton_tester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_testerActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_tester, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 267, -1, -1));

        text_lbl_nb_chiffres_exacts.setText("Nombre de chiffres exacts : ");
        text_lbl_nb_chiffres_exacts.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(text_lbl_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 344, -1, -1));

        text_nb_chiffres_exacts.setText("0");
        getContentPane().add(text_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 345, 18, -1));

        text_lbl_nb_chiffres_haut.setText("Nombre de chiffres trop haut :");
        text_lbl_nb_chiffres_haut.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(text_lbl_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 396, -1, -1));

        text_nb_chiffres_haut.setText("0");
        getContentPane().add(text_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 397, 17, -1));

        text_lbl_nb_chiffres_bas.setText("Nombre de chiffres trop bas : ");
        text_lbl_nb_chiffres_bas.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(text_lbl_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 480, -1, -1));

        text_nb_chiffre_bas.setText("0");
        getContentPane().add(text_nb_chiffre_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 481, 29, -1));

        texte_score.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        texte_score.setText("0 / 5");
        getContentPane().add(texte_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 379, 62, 42));

        text_tentatives.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        text_tentatives.setText("Tentatives");
        getContentPane().add(text_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 344, -1, -1));

        bouton_recommencer.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        bouton_recommencer.setText("Recommencer");
        bouton_recommencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_recommencerActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 473, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Trouvez le bon code en moins de 5 tentatives !");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 6, 298, 28));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed
        int valeur = Integer.parseInt(text_chiffre_0.getText());

if (valeur < 9) {
    valeur++;
} else {
    valeur = 0;
}

text_chiffre_0.setText(String.valueOf(valeur));

    }//GEN-LAST:event_up_chiffre_1ActionPerformed

    private void up_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_3ActionPerformed
        int valeur = Integer.parseInt(text_chiffre_2.getText());

if (valeur < 9) {
    valeur++;
} else {
    valeur = 0;
}

text_chiffre_2.setText(String.valueOf(valeur));

    }//GEN-LAST:event_up_chiffre_3ActionPerformed

    private void up_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_2ActionPerformed
        int valeur = Integer.parseInt(text_chiffre_1.getText());

if (valeur < 9) {
    valeur++;
} else {
    valeur = 0;
}

text_chiffre_1.setText(String.valueOf(valeur));

    }//GEN-LAST:event_up_chiffre_2ActionPerformed

    private void down_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_2ActionPerformed
        int valeur = Integer.parseInt(text_chiffre_1.getText());

if (valeur > 0) {
    valeur--;
} else {
    valeur = 9;
}

text_chiffre_1.setText(String.valueOf(valeur));

    }//GEN-LAST:event_down_chiffre_2ActionPerformed

    private void up_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_4ActionPerformed
        int valeur = Integer.parseInt(text_chiffre_3.getText());

if (valeur > 0) {
    valeur--;
} else {
    valeur = 9;
}

    }//GEN-LAST:event_up_chiffre_4ActionPerformed

    private void down_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_1ActionPerformed
        int valeur = Integer.parseInt(text_chiffre_0.getText());

if (valeur > 0) {
    valeur--;
} else {
    valeur = 9;
}

text_chiffre_0.setText(String.valueOf(valeur));

    }//GEN-LAST:event_down_chiffre_1ActionPerformed

    private void down_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_3ActionPerformed
        int valeur = Integer.parseInt(text_chiffre_2.getText());

if (valeur > 0) {
    valeur--;
} else {
    valeur = 9;
}

text_chiffre_2.setText(String.valueOf(valeur));

    }//GEN-LAST:event_down_chiffre_3ActionPerformed

    private void down_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_4ActionPerformed
        int valeur = Integer.parseInt(text_chiffre_3.getText());

if (valeur > 0) {
    valeur--;
} else {
    valeur = 9;
}

text_chiffre_3.setText(String.valueOf(valeur));

    }//GEN-LAST:event_down_chiffre_4ActionPerformed

    private void bouton_recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_recommencerActionPerformed
        jeu.nouvellePartie();

// remettre les chiffres à 0
text_chiffre_0.setText("0");
text_chiffre_1.setText("0");
text_chiffre_2.setText("0");
text_chiffre_3.setText("0");

// remettre les résultats à 0
text_nb_chiffres_exacts.setText("0");
text_nb_chiffres_haut.setText("0");
text_nb_chiffre_bas.setText("0");

// remettre les tentatives
text_tentatives.setText("10 / 10");

    }//GEN-LAST:event_bouton_recommencerActionPerformed

    private void bouton_testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_testerActionPerformed
 int[] essai = new int[4];

essai[0] = Integer.parseInt(text_chiffre_0.getText());
essai[1] = Integer.parseInt(text_chiffre_1.getText());
essai[2] = Integer.parseInt(text_chiffre_2.getText());
essai[3] = Integer.parseInt(text_chiffre_3.getText());

int[] resultat = jeu.verifierEssai(essai);
if (resultat != null) {
    if (resultat != null) {
    text_nb_chiffres_exacts.setText(String.valueOf(resultat[0]));
    text_nb_chiffres_haut.setText(String.valueOf(resultat[1]));
    text_nb_chiffre_bas.setText(String.valueOf(resultat[2]));
    text_tentatives.setText(jeu.getTentativesRestantes() + " / 10");
}
}
 
    }//GEN-LAST:event_bouton_testerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new graphique1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JButton bouton_tester;
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel text_chiffre_0;
    private javax.swing.JLabel text_chiffre_1;
    private javax.swing.JLabel text_chiffre_2;
    private javax.swing.JLabel text_chiffre_3;
    private javax.swing.JLabel text_lbl_nb_chiffres_bas;
    private javax.swing.JLabel text_lbl_nb_chiffres_exacts;
    private javax.swing.JLabel text_lbl_nb_chiffres_haut;
    private javax.swing.JLabel text_nb_chiffre_bas;
    private javax.swing.JLabel text_nb_chiffres_exacts;
    private javax.swing.JLabel text_nb_chiffres_haut;
    private javax.swing.JLabel text_tentatives;
    private javax.swing.JLabel texte_score;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    // End of variables declaration//GEN-END:variables
}
