/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kassab10
 */
public class graphique1 extends javax.swing.JFrame {
    private Combinaisons jeu;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(graphique1.class.getName());

    /**
     * Creates new form graphique1
     */
    public graphique1() {
        initComponents();
        jeu = new Combinaisons();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        up_chiffre_1 = new javax.swing.JButton();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();
        up_chiffre_4 = new javax.swing.JButton();
        text_chiffre_0 = new javax.swing.JLabel();
        text_chiffre_1 = new javax.swing.JLabel();
        text_chiffre_2 = new javax.swing.JLabel();
        text_chiffre_3 = new javax.swing.JLabel();
        down_chiffre_1 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();
        bouton_tester = new javax.swing.JButton();
        text_lbl_nb_chiffres_exacts = new javax.swing.JLabel();
        text_nb_chiffres_exacts = new javax.swing.JLabel();
        text_lbl_nb_chiffres_haut = new javax.swing.JLabel();
        text_nb_chiffres_haut = new javax.swing.JLabel();
        text_lbl_nb_chiffres_bas = new javax.swing.JLabel();
        text_nb_chiffre_bas = new javax.swing.JLabel();
        texte_score = new javax.swing.JLabel();
        text_tentatives = new javax.swing.JLabel();
        bouton_recommencer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        up_chiffre_1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        up_chiffre_1.setText("^");
        up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_1ActionPerformed(evt);
            }
        });

        up_chiffre_2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        up_chiffre_2.setText("^");
        up_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_2ActionPerformed(evt);
            }
        });

        up_chiffre_3.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        up_chiffre_3.setText("^");
        up_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_3ActionPerformed(evt);
            }
        });

        up_chiffre_4.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        up_chiffre_4.setText("^");
        up_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_4ActionPerformed(evt);
            }
        });

        text_chiffre_0.setText("0");

        text_chiffre_1.setText("0");

        text_chiffre_2.setText("0");

        text_chiffre_3.setText("0");

        down_chiffre_1.setText("down");
        down_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_1ActionPerformed(evt);
            }
        });

        down_chiffre_2.setText("Down");
        down_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_2ActionPerformed(evt);
            }
        });

        down_chiffre_3.setText("Down");
        down_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_3ActionPerformed(evt);
            }
        });

        down_chiffre_4.setText("Down");
        down_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_4ActionPerformed(evt);
            }
        });

        bouton_tester.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        bouton_tester.setText("Tester");
        bouton_tester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_testerActionPerformed(evt);
            }
        });

        text_lbl_nb_chiffres_exacts.setText("Nombre de chiffres exacts : ");
        text_lbl_nb_chiffres_exacts.setBorder(new javax.swing.border.MatteBorder(null));

        text_nb_chiffres_exacts.setText("0");

        text_lbl_nb_chiffres_haut.setText("Nombre de chiffres trop haut :");
        text_lbl_nb_chiffres_haut.setBorder(new javax.swing.border.MatteBorder(null));

        text_nb_chiffres_haut.setText("0");

        text_lbl_nb_chiffres_bas.setText("Nombre de chiffres trop bas : ");
        text_lbl_nb_chiffres_bas.setBorder(new javax.swing.border.MatteBorder(null));

        text_nb_chiffre_bas.setText("0");

        texte_score.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        texte_score.setText("0 / 5");

        text_tentatives.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        text_tentatives.setText("Tentatives");

        bouton_recommencer.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        bouton_recommencer.setText("Recommencer");
        bouton_recommencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_recommencerActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Trouvez le bon code en moins de 5 tentatives !");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(138, 138, 138)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(text_lbl_nb_chiffres_exacts)
                                    .addGap(242, 242, 242)
                                    .addComponent(text_chiffre_2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(up_chiffre_3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(text_chiffre_3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(up_chiffre_2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(text_lbl_nb_chiffres_bas)
                                .addComponent(text_lbl_nb_chiffres_haut)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(34, 34, 34)
                                    .addComponent(text_chiffre_0, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                                    .addComponent(text_chiffre_1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(text_nb_chiffre_bas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(text_nb_chiffres_haut, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(208, 208, 208)
                                                .addComponent(texte_score, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(text_nb_chiffres_exacts, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(169, 169, 169)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(bouton_recommencer)
                                                    .addComponent(text_tentatives))))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(413, 413, 413)
                                .addComponent(up_chiffre_4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(92, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addComponent(bouton_tester)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(up_chiffre_1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(down_chiffre_1)
                        .addGap(105, 105, 105)
                        .addComponent(down_chiffre_2)
                        .addGap(128, 128, 128)
                        .addComponent(down_chiffre_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(down_chiffre_4)
                        .addGap(79, 79, 79))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(up_chiffre_1)
                                    .addComponent(up_chiffre_3)
                                    .addComponent(up_chiffre_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(36, 36, 36)
                                .addComponent(text_chiffre_1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(text_chiffre_0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_chiffre_2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(down_chiffre_1)
                            .addComponent(down_chiffre_2)
                            .addComponent(down_chiffre_3))
                        .addGap(71, 71, 71)
                        .addComponent(bouton_tester)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(text_nb_chiffres_exacts)
                                    .addComponent(text_lbl_nb_chiffres_exacts))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(text_nb_chiffres_haut)
                                    .addComponent(text_lbl_nb_chiffres_haut))
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(text_tentatives)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(texte_score, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_lbl_nb_chiffres_bas)
                            .addComponent(text_nb_chiffre_bas)
                            .addComponent(bouton_recommencer))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(up_chiffre_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_chiffre_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(down_chiffre_4)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed
        int valeur = Integer.parseInt(text_chiffre_0.getText());

if (valeur < 9) {
    valeur++;
} else {
    valeur = 0;
}

text_chiffre_0.setText(String.valueOf(valeur));

    }//GEN-LAST:event_up_chiffre_1ActionPerformed

    private void up_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_3ActionPerformed
        int valeur = Integer.parseInt(text_chiffre_2.getText());

if (valeur < 9) {
    valeur++;
} else {
    valeur = 0;
}

text_chiffre_2.setText(String.valueOf(valeur));

    }//GEN-LAST:event_up_chiffre_3ActionPerformed

    private void up_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_2ActionPerformed
        int valeur = Integer.parseInt(text_chiffre_1.getText());

if (valeur < 9) {
    valeur++;
} else {
    valeur = 0;
}

text_chiffre_1.setText(String.valueOf(valeur));

    }//GEN-LAST:event_up_chiffre_2ActionPerformed

    private void down_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_2ActionPerformed
        int valeur = Integer.parseInt(text_chiffre_1.getText());

if (valeur > 0) {
    valeur--;
} else {
    valeur = 9;
}

text_chiffre_1.setText(String.valueOf(valeur));

    }//GEN-LAST:event_down_chiffre_2ActionPerformed

    private void up_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_4ActionPerformed
        int valeur = Integer.parseInt(text_chiffre_3.getText());

if (valeur > 0) {
    valeur--;
} else {
    valeur = 9;
}

    }//GEN-LAST:event_up_chiffre_4ActionPerformed

    private void down_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_1ActionPerformed
        int valeur = Integer.parseInt(text_chiffre_0.getText());

if (valeur > 0) {
    valeur--;
} else {
    valeur = 9;
}

text_chiffre_0.setText(String.valueOf(valeur));

    }//GEN-LAST:event_down_chiffre_1ActionPerformed

    private void down_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_3ActionPerformed
        int valeur = Integer.parseInt(text_chiffre_2.getText());

if (valeur > 0) {
    valeur--;
} else {
    valeur = 9;
}

text_chiffre_2.setText(String.valueOf(valeur));

    }//GEN-LAST:event_down_chiffre_3ActionPerformed

    private void down_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_4ActionPerformed
        int valeur = Integer.parseInt(text_chiffre_3.getText());

if (valeur > 0) {
    valeur--;
} else {
    valeur = 9;
}

text_chiffre_3.setText(String.valueOf(valeur));

    }//GEN-LAST:event_down_chiffre_4ActionPerformed

    private void bouton_recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_recommencerActionPerformed
        jeu.nouvellePartie();

// remettre les chiffres à 0
text_chiffre_0.setText("0");
text_chiffre_1.setText("0");
text_chiffre_2.setText("0");
text_chiffre_3.setText("0");

// remettre les résultats à 0
text_nb_chiffres_exacts.setText("0");
text_nb_chiffres_haut.setText("0");
text_nb_chiffre_bas.setText("0");

// remettre les tentatives
text_tentatives.setText("10 / 10");

    }//GEN-LAST:event_bouton_recommencerActionPerformed

    private void bouton_testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_testerActionPerformed
 int[] essai = new int[4];

essai[0] = Integer.parseInt(text_chiffre_0.getText());
essai[1] = Integer.parseInt(text_chiffre_1.getText());
essai[2] = Integer.parseInt(text_chiffre_2.getText());
essai[3] = Integer.parseInt(text_chiffre_3.getText());

int[] resultat = jeu.verifierEssai(essai);
if (resultat != null) {
    if (resultat != null) {
    text_nb_chiffres_exacts.setText(String.valueOf(resultat[0]));
    text_nb_chiffres_haut.setText(String.valueOf(resultat[1]));
    text_nb_chiffre_bas.setText(String.valueOf(resultat[2]));
    text_tentatives.setText(jeu.getTentativesRestantes() + " / 10");
}
}
 
    }//GEN-LAST:event_bouton_testerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new graphique1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JButton bouton_tester;
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel text_chiffre_0;
    private javax.swing.JLabel text_chiffre_1;
    private javax.swing.JLabel text_chiffre_2;
    private javax.swing.JLabel text_chiffre_3;
    private javax.swing.JLabel text_lbl_nb_chiffres_bas;
    private javax.swing.JLabel text_lbl_nb_chiffres_exacts;
    private javax.swing.JLabel text_lbl_nb_chiffres_haut;
    private javax.swing.JLabel text_nb_chiffre_bas;
    private javax.swing.JLabel text_nb_chiffres_exacts;
    private javax.swing.JLabel text_nb_chiffres_haut;
    private javax.swing.JLabel text_tentatives;
    private javax.swing.JLabel texte_score;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    // End of variables declaration//GEN-END:variables
}
