
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kassab10
 */
public class FenetreQuizz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuizz.class.getName());
    
    private ArrayList<Questions> listQuestions = new ArrayList<> () ; 
    private int indexQuestionsCourante = 0 ; 
    private int score = 0 ; 
    /**
     * Creates new form FenetreQuizz
     */
    public FenetreQuizz() {
        initComponents();
        Score.setText("Score : " + Score);
        //Questions :
        listQuestions.add(new Questions (" Combien font 2 + 2 ?", "1" , "2" , "3" , "4", 4));
        listQuestions.add(new Questions ("Quelle est la capitale du Liban ? " , "Abidjan" , "Beirut" , "Paris" , "Caire",2)) ;
        listQuestions.add(new Questions ("Combien de saisons il y'a ? " , "1" , "5" , "4" , "2",3)) ;
        listQuestions.add(new Questions ("Quelle est la couleur du soleil ? " , "Jaune" , "Bleu" , "Gris" , "Vert",1)) ;
        listQuestions.add(new Questions ("Combien de jours dans la semaine ? " , "4" , "7" , "9" , "10",2)) ;
    }  
    private void afficherQuestionCourante() {

   Questions q = listQuestions.get(indexQuestionsCourante);

    question.setText(q.getIntitule());

    bouton1.setText(q.getProposition1());
    bouton2.setText(q.getProposition2());
    bouton3.setText(q.getProposition3());
    bouton4.setText(q.getProposition4());

    bouton1.setEnabled(true);
    bouton2.setEnabled(true);
    bouton3.setEnabled(true);
    bouton4.setEnabled(true);

    message.setText("");    
}
    private void verifierReponse(int choix) {

    Questions q = listQuestions.get(indexQuestionsCourante);

    // Vérifier la réponse
    if (choix == q.getIndexBonneReponse()) {
        message.setText("Bonne réponse !");
        score++;  // incrémente ton score
        Score.setText("Score : " + score);
    } 
    else {
        message.setText("Mauvaise réponse !");
    }

    // Désactiver les boutons pour empêcher de cliquer encore
    bouton1.setEnabled(false);
    bouton2.setEnabled(false);
    bouton3.setEnabled(false);
    bouton4.setEnabled(false);
}

        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        question = new javax.swing.JLabel();
        bouton1 = new javax.swing.JButton();
        bouton2 = new javax.swing.JButton();
        bouton3 = new javax.swing.JButton();
        bouton4 = new javax.swing.JButton();
        message = new javax.swing.JLabel();
        Score = new javax.swing.JLabel();
        suivant = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        question.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        question.setForeground(new java.awt.Color(0, 153, 153));
        question.setText("Question");
        getContentPane().add(question, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 280, 60));

        bouton1.setFont(new java.awt.Font("Kohinoor Bangla", 1, 14)); // NOI18N
        bouton1.setForeground(new java.awt.Color(0, 102, 204));
        bouton1.setText("1");
        bouton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton1ActionPerformed(evt);
            }
        });
        getContentPane().add(bouton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 134, 30));

        bouton2.setFont(new java.awt.Font("Kohinoor Bangla", 3, 14)); // NOI18N
        bouton2.setForeground(new java.awt.Color(0, 102, 204));
        bouton2.setText("2");
        bouton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton2ActionPerformed(evt);
            }
        });
        getContentPane().add(bouton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 134, 30));

        bouton3.setFont(new java.awt.Font("Kohinoor Bangla", 1, 14)); // NOI18N
        bouton3.setForeground(new java.awt.Color(0, 102, 204));
        bouton3.setText("3");
        bouton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton3ActionPerformed(evt);
            }
        });
        getContentPane().add(bouton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 134, -1));

        bouton4.setFont(new java.awt.Font("Kohinoor Bangla", 1, 14)); // NOI18N
        bouton4.setForeground(new java.awt.Color(0, 102, 204));
        bouton4.setText("4");
        bouton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton4ActionPerformed(evt);
            }
        });
        getContentPane().add(bouton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 134, 30));

        message.setFont(new java.awt.Font("Kohinoor Bangla", 3, 18)); // NOI18N
        message.setForeground(new java.awt.Color(0, 153, 51));
        message.setText("Bonne réponse");
        getContentPane().add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 210, 70));

        Score.setFont(new java.awt.Font("Kohinoor Bangla", 1, 12)); // NOI18N
        Score.setForeground(new java.awt.Color(204, 204, 204));
        Score.setText("Score ");
        getContentPane().add(Score, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 57, 89, 47));

        suivant.setFont(new java.awt.Font("Kohinoor Bangla", 1, 24)); // NOI18N
        suivant.setForeground(new java.awt.Color(153, 153, 0));
        suivant.setText("Question suivante");
        suivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suivantActionPerformed(evt);
            }
        });
        getContentPane().add(suivant, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bouton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton1ActionPerformed
        verifierReponse(1);
    }//GEN-LAST:event_bouton1ActionPerformed

    private void bouton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton2ActionPerformed
        verifierReponse(2);
    }//GEN-LAST:event_bouton2ActionPerformed

    private void bouton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton3ActionPerformed
        verifierReponse(3);
    }//GEN-LAST:event_bouton3ActionPerformed

    private void suivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suivantActionPerformed

    indexQuestionsCourante++;

    if (indexQuestionsCourante < listQuestions.size()) {

        afficherQuestionCourante();
    } 
    else {
        question.setText("Quiz terminé !");
        message.setText("Score final : " + score + " / " + listQuestions.size());

        bouton1.setEnabled(false);
        bouton2.setEnabled(false);
        bouton3.setEnabled(false);
        bouton4.setEnabled(false);

    
        suivant.setEnabled(false);
    }
    }//GEN-LAST:event_suivantActionPerformed

    private void bouton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton4ActionPerformed
        verifierReponse(4);   
    }//GEN-LAST:event_bouton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreQuizz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Score;
    private javax.swing.JButton bouton1;
    private javax.swing.JButton bouton2;
    private javax.swing.JButton bouton3;
    private javax.swing.JButton bouton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel message;
    private javax.swing.JLabel question;
    private javax.swing.JButton suivant;
    // End of variables declaration//GEN-END:variables
}
